version: '3.8'

services:
 
  postgres_db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: albumuser
      POSTGRES_PASSWORD: albump@ss
    ports:
      - 5432:5432
    container_name: postgres_db
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      # - /var/lib/postgresql/data
      - ./data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    # hostname: "adminer.local"

  portainer:
    image: portainer/portainer
    container_name: "portainer"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: -H unix:///var/run/docker.sock --admin-password '$$2y$$05$$G4dP9ooT0i7gSionG0I1cu45UCwc7kFM/DUucgMDvFcd59ukrmfwS'
    ports:
      - 9000:9000

networks:
  default:
    external:
      name: albumbackend_net